# site settings
title: Stonehead Park's on the way
email: shoark7@gmail.com
description: Blog for dev, knowledge, expressing my thoughts. Managed by Stonehead Park. 
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://ok.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  shoark7
google_username: shoark7

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

sass:
  style: compressed


# customized variable
all: all






          
# Build settings
markdown: kramdown
kramdown:
        input: GFM  # Supports github flavored markdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
